### ISSUE TITLE
Adding some Security CTF Platforms!

### ISSUE THREAD

**Issue by TaharAmine** [open-minds/awesome-openminds-team#39]
## Summery:
I want to request you to add the following CTF Platforms to your list:

- HackTheBox (Known as HTB): [HTB](https://www.hackthebox.eu/)
- VulnHub: [VulnHub](https://www.vulnhub.com/)
- Awesome Curated List of Environments and Platforms for Hacking and CTFs: [Link](https://mrtaharamine.blogspot.com/2018/02/hacking-environments-and-platforms.html)

**Comment by Fcmam5** [comment]
Salam Amine! Thank you very much for your contribution, feel free to create a pull request, and add these awesome resources under a new category in [/#Chosen Websites](https://github.com/open-minds/awesome-openminds-team#chosen-websites), name it (for example) Cybersecurity and pentesting.
