### ISSUE TITLE
Misplaced link in readme.

### ISSUE THREAD

**Issue by sidou01** [open-minds/awesome-openminds-team#54]
Under Chosen Websites in the studies section there is a misplaced YouTube link **(MiftaSintaha's YouTube channel : Computer sciences video tutorials)**  that should be in **Good YouTube channels** section.

**Comment by Fcmam5** [comment]
Thank you @sidou01 please feel free to fix it, or let's keep this issue people who want to do their first contribution :smile:

**Comment by sidou01** [comment]
Sounds good :+1: . I'll leave it for people who want to submit their first PR !

**Comment by vivmost** [comment]
I'll do it.

**Comment by vivmost** [comment]
I have sent the PR.

**Comment by vivmost** [comment]
I have accidently sent the PR related to this issue along with #58 and it got merged.

**Comment by Fcmam5** [comment]
Awesome @vivmost ! Thank you for fixing it 😄
